export interface IMockData {
  id: number;
  Name: string;
  Author: string;
  Tage: string;
  Link: string;
  Rating: number;
  Mag: string;
}

export const mockDataBook = [
  {
    id: 1,
    Name: "Затерянный мир",
    Author: "Артур Дойл",
    Tage: "Детектив",
    Link: "https://www.labirint.ru/books/872576/",
    Rating: 9.09,
    Mag: "Лабиринт",
  },
  {
    id: 2,
    Name: "Земля Санникова",
    Author: "Владимир Обручев",
    Tage: "Фантастика",
    Link: "https://www.labirint.ru/books/795058/",
    Rating: 8.43,
    Mag: "Лабиринт",
  },
  {
    id: 3,
    Name: "Задача трех тел",
    Author: "Цысинь Лю",
    Tage: "Научная фантастика",
    Link: "https://www.labirint.ru/books/610958/",
    Rating: 8.94,
    Mag: "Лабиринт",
  },
  {
    id: 4,
    Name: "Падение, или Додж в Аду",
    Author: "Нил Стивенсон",
    Tage: "Фантастика",
    Link: "https://www.labirint.ru/books/1009686/",
    Rating: 0.0,
    Mag: "Лабиринт",
  },
  {
    id: 5,
    Name: "Галактическая одиссея",
    Author: "Сергей Снегов",
    Tage: "Фантастика",
    Link: "https://www.labirint.ru/books/1006542/",
    Rating: 10.0,
    Mag: "Лабиринт",
  },
  {
    id: 6,
    Name: "Принцесса Дюны",
    Author: "Герберт, Андерсон",
    Tage: "Научная фантастика",
    Link: "https://www.labirint.ru/books/1007747/",
    Rating: 0.0,
    Mag: "Лабиринт",
  },
  {
    id: 7,
    Name: "Космоолухи. Киберканикулы",
    Author: "Ольга Громыко",
    Tage: "Фантастика",
    Link: "https://www.labirint.ru/books/970725/",
    Rating: 9.0,
    Mag: "Лабиринт",
  },
  {
    id: 8,
    Name: "Темный лес",
    Author: "Цысинь Лю",
    Tage: "Научная фантастика",
    Link: "https://www.labirint.ru/books/622004/",
    Rating: 9.34,
    Mag: "Лабиринт",
  },
  {
    id: 9,
    Name: "Лабиринт чародея. Вымыслы, грезы и химеры",
    Author: "Кларк Смит",
    Tage: "Фантастика",
    Link: "https://www.labirint.ru/books/1000597/",
    Rating: 10.0,
    Mag: "Лабиринт",
  },
  {
    id: 10,
    Name: "О муравьях и динозаврах. Песня кита",
    Author: "Цысинь Лю",
    Tage: "Научная фантастика",
    Link: "https://www.labirint.ru/books/980132/",
    Rating: 8.86,
    Mag: "Лабиринт",
  },
  {
    id: 11,
    Name: "Князья Ада",
    Author: "Барбара Хэмбли",
    Tage: "Фантастика",
    Link: "https://www.labirint.ru/books/1009448/",
    Rating: 0.0,
    Mag: "Лабиринт",
  },
  {
    id: 12,
    Name: "Джек из Тени",
    Author: "Роджер Желязны",
    Tage: "Фантастика",
    Link: "https://www.labirint.ru/books/932882/",
    Rating: 9.75,
    Mag: "Лабиринт",
  },
  {
    id: 13,
    Name: "Сквозь зеркала. Книга 3. Память Вавилона",
    Author: "Кристель Дабо",
    Tage: "Фантастика",
    Link: "https://www.labirint.ru/books/656274/",
    Rating: 9.4,
    Mag: "Лабиринт",
  },
  {
    id: 14,
    Name: "Путешествие в Элевсин",
    Author: "Виктор Пелевин",
    Tage: "Фантастика",
    Link: "https://www.litres.ru/book/viktor-pelevin/puteshestvie-v-elevsin-69586360/",
    Rating: 4.0,
    Mag: "Литрес",
  },
  {
    id: 15,
    Name: "KGBT+ (КГБТ+)",
    Author: "Виктор Пелевин",
    Tage: "Фантастика",
    Link: "https://www.litres.ru/book/viktor-pelevin/kgbt-kgbt-68010821/",
    Rating: 4.0,
    Mag: "Литрес",
  },
  {
    id: 16,
    Name: "1984",
    Author: "Джордж Оруэлл",
    Tage: "Фантастика",
    Link: "https://www.litres.ru/audiobook/dzhordzh-oruell/1984-63576652/",
    Rating: 4.0,
    Mag: "Литрес",
  },
  {
    id: 17,
    Name: "Человек-невидимка",
    Author: "Герберт Джордж Уэллс",
    Tage: "Фантастика",
    Link: "https://www.litres.ru/audiobook/gerbert-uells/chelovek-nevidimka-22208259/",
    Rating: 4.5,
    Mag: "Литрес",
  },
  {
    id: 18,
    Name: "Маракотова бездна",
    Author: "Артур Конан Дойл",
    Tage: "Фантастика",
    Link: "https://www.litres.ru/audiobook/arthur-konan-doyle/marakotova-bezdna-173316/",
    Rating: 4.6,
    Mag: "Литрес",
  },
  {
    id: 19,
    Name: "Приключения Шерлока Холмса",
    Author: "Артур Конан Дойл",
    Tage: "Детектив",
    Link: "https://www.litres.ru/audiobook/arthur-konan-doyle/priklucheniya-sherloka-holmsa-rasskazy-6003302/",
    Rating: 4.7,
    Mag: "Литрес",
  },
  {
    id: 20,
    Name: "Голова профессора Доуэля",
    Author: "Александр Беляев",
    Tage: "Научная фантастика",
    Link: "https://www.litres.ru/audiobook/aleksandr-belyaev/golova-professora-douelya-22469378/",
    Rating: 0.0,
    Mag: "Литрес",
  },
];

export const mockDet = [
  {
    id: 1,
    Name: "Затерянный мир",
    Author: "Артур Дойл",
    Tage: "Детектив",
    Link: "https://www.labirint.ru/books/872576/",
    Rating: 9.09,
    Mag: "Лабиринт",
  },
  {
    id: 19,
    Name: "Приключения Шерлока Холмса",
    Author: "Артур Конан Дойл",
    Tage: "Детектив",
    Link: "https://www.litres.ru/audiobook/arthur-konan-doyle/priklucheniya-sherloka-holmsa-rasskazy-6003302/",
    Rating: 4.7,
    Mag: "Литрес",
  },
];
